#pragma once

enum class OperationCode
{
	STOP,
	CHECK_SIZE,
    CHECK_EMAIL,
    CHECK_LOGIN,
    REGISTRATION,
	SIGN_IN,
    NEW_MESSAGES_IN_COMMON_CHAT,
    NEW_MESSAGES_IN_PRIVATE_CHAT,
    GET_NUMBER_MESSAGES_IN_CHAT,
    COMMON_CHAT_GET_MESSAGES,
    COMMON_CHAT_ADD_MESSAGE,
    COMMON_CHAT_CHECK_MESSAGE,
    PRIVATE_CHAT_CHECK_MESSAGE,
    COMMON_CHAT_EDIT_MESSAGE,
    COMMON_CHAT_DELETE_MESSAGE,
    VIEW_USERS_ID_NAME_SURNAME,
    VIEW_USERS_WITH_NEW_MESSAGES,
    VIEW_USERS_WITH_PRIVATE_CHAT,
    GET_PRIVATE_CHAT_ID,
    PRIVATE_CHAT_ADD_MESSAGE,
    PRIVATE_CHAT_GET_MESSAGES,
    PRIVATE_CHAT_EDIT_MESSAGE,
    PRIVATE_CHAT_DELETE_MESSAGE,
	READY,
	ERROR,
};

const int HEADER_SIZE = 256;

